services:
  backend:
    build: .
    ports:
      - "8010:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    command: sh -c "chmod +x ./docker/app.sh && ./docker/app.sh"
    depends_on:
      - db


  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data/


volumes:
  db_data:
