# Generated by Django 5.1.2 on 2024-10-22 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000)),
                ('first_answer', models.TextField(max_length=300)),
                ('second_answer', models.TextField(blank=True, max_length=300, null=True)),
                ('third_answer', models.TextField(blank=True, max_length=300, null=True)),
                ('fourth_answer', models.TextField(blank=True, max_length=300, null=True)),
                ('description', models.TextField(blank=True, max_length=300, null=True)),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
    ]
