# Generated by Django 5.1.2 on 2024-10-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='valid_answer_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
