# Generated by Django 5.1.2 on 2024-11-26 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employee_tg_id'),
        ('survey', '0003_dailysurveycounter'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailysurveycounter',
            unique_together={('employee', 'date')},
        ),
    ]
