# Generated by Django 5.1.2 on 2024-12-17 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_alter_dailysurveycounter_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
